[DM]
n_rings = 4   # number of hexagonal segment rings
hex_side = 2. # [m] hexagonal side length
hex_gap = 0.4 # [m] gap between hexagonal segments

[OPT]
pixel_scale = 100. # pixels per meter
opt_radius = 50.   # [m] pupil radius
cw_rot_angle = 0.  # [rad] clockwise pupil rotation angle about optical axis